language: python
python:
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

sudo: required

# install dependencies for scipy
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

# install linguistica
install:
  - python setup.py install

# run tests
script:
  - bash pytest_run.sh
