language: python
python:
  - "3.4"
  - "3.5"

sudo: required

# install dependencies: numpy, scipy, networkx
# for scipy, {libblas-dev liblapack-dev libatlas-base-dev gfortran} are needed
# we use coveralls for measuring test coverage
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install -I numpy>=1.10.4
  - pip install -I scipy>=0.17.0
  - pip install -I networkx>=1.11
  - pip install coveralls

# install linguistica
install:
  - python setup.py install

# run tests
script:
  - bash pytest_run.sh

after_success:
  - coveralls
