language: python
python:
  - "3.4"
  - "3.5"

sudo: required

# install dependencies for scipy
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install -I networkx>=1.11
  - pip install -I scipy>=0.17.0
  - pip install -I numpy>=1.10.4

# install linguistica
install:
  - python setup.py install

# run tests
script:
  - bash pytest_run.sh
