# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

virtualenv:
  system_site_packages: true

env:
  matrix:
    - PYTHON_VERSION="3.4"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"

install:
  - source ci/travis_install.sh

script:
  - pytest -v

after_success:
  - coveralls

cache: apt

sudo: false
