# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "3.4"
  - "3.5"

sudo: required

# for scipy, {libblas-dev liblapack-dev libatlas-base-dev gfortran} are needed
# test_requirements.txt packages for running tests and measuring coverage
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install -r test_requirements.txt

# install linguistica
install:
  - python setup.py install

# run tests using nose
# specify "--where=tests" as all tests are in the directory "tests"
script:
  - nosetests --where=tests --with-coverage

after_success:
  - coveralls
