language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
  - pytest -vv --cov linguistica
  - flake8 linguistica
