# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "3.4"
  - "3.5"

sudo: required

before_install:
  - bash ci/travis_install.sh

# install linguistica
install:
  - python setup.py install

# run tests using nose
script:
  - python nosetests_run.py

after_success:
  - coveralls
