language: python
python:
  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

sudo: required

# install dependencies
install:
  - python setup.py install

# run tests
script:
  - bash pytest_run.sh
